language: r
cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin

r_binary_packages:
  - rgdal

r:
    - release
    - devel

after_success:
    - Rscript -e 'covr::codecov()'
