language: r
cache: packages

# This did not help
#before_install:
#  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'

# What happens when I remove rgdal? Where is the failure?
#addons:
#  apt:
#    packages:
#      - libudunits2-dev
#      - gdal-bin
#      - libgdal-dev

#r_binary_packages:
#  - rgdal

r:
    - release
    - devel

r_packages:
    - covr

#after_success:
#    - Rscript -e 'covr::codecov()'
