language: r
cache: packages

# Trying this
#repos: 
#  CRAN: https://cran.rstudio.com
#  rforge: http://R-Forge.R-project.org

addons:
  apt:
    packages:
      - libudunits2-dev
      - gdal-bin
      - libgdal-dev

#r_binary_packages:
#  - rgdal
before_install:
- R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'

r:
    - oldrel
    - release
    - devel

r_packages:
    - covr

#after_success:
#    - Rscript -e 'covr::codecov()'
